### ISSUE TITLE
explain_weights didn't work in Python 3.5.1 (LIME)

### ISSUE THREAD

**Issue by Amarchuk** [TeamHG-Memex/eli5#243]
Hi, 

I try to use ELI5 explainer for numerical data in LIME-manner like you provide in https://github.com/TeamHG-Memex/eli5/blob/master/notebooks/LIME%20and%20synthetic%20data.ipynb, but get next traceback (both on Windows and Linux machines):

```bash
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    feature_names=feature_names)
  File "/opt/app-root/src/xai/eli5_explainer.py", line 49, in explain_decision
    expl = eli5.explain_weights(est, target_names=target_names, feature_names=feature_names, top=(5, 5))
  File "/opt/app-root/lib/python3.5/site-packages/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/app-root/lib/python3.5/site-packages/eli5/sklearn/explain_weights.py", line 222, in explain_linear_classifier_weights
    feature_re=feature_re,
  File "/opt/app-root/lib/python3.5/site-packages/eli5/sklearn/utils.py", line 126, in get_feature_names_filtered
    estimator_feature_names=estimator_feature_names,
  File "/opt/app-root/lib/python3.5/site-packages/eli5/sklearn/utils.py", line 97, in get_feature_names
    if feature_names.n_features != num_features:
AttributeError: 'list' object has no attribute 'n_features'
```

This is because  in Python 3.5.1 
```bash
type(feature_names): <class 'list'>
isinstance(feature_names, FeatureNames): True
feature_names.__class__ is FeatureNames: False
```
while in Python 3.5.3 all works fine (I didn't test in 3.5.2). All this possibly due to some strange behaviour of typing module on subclasses of Iterable (like FeatureNames).  But I can't find any mention of something similar in Python versions changelogs. 

So at least part of the code didn't work in any version of Python>3.4 as docs states. Fix this will be really easy, for example just change ```isinstance(feature_names, FeatureNames)``` to ```isinstance(feature_names, FeatureNames) & hasattr(feature_names, 'n_features')```.

Thanks
